
Neos:
  Flow:
    error:
      exceptionHandler:
        defaultRenderingOptions:
          templatePathAndFilename: 'resource://Neos.IdNeosIo/Private/Templates/Error/Default.html'
        renderingGroups:
          notFoundExceptions:
            options:
              viewOptions:
                templatePathAndFilename: 'resource://Neos.IdNeosIo/Private/Templates/Error/Default.html'
          databaseConnectionExceptions:
            options:
              viewOptions:
                templatePathAndFilename: 'resource://Neos.IdNeosIo/Private/Templates/Error/Default.html'
          invalidTokenExceptions:
            matchingExceptionClassNames:
              - Neos\IdNeosIo\Security\Authentication\InvalidTokenException
            options:
              variables:
                errorDescription: "The token hash is invalid or expired!\nMake sure that the token link is complete.\n"
              viewOptions: {  }
    security:
      authentication:
        providers:
          TokenProvider:
            provider: Neos\IdNeosIo\Security\Authentication\TokenProvider
            providerOptions:
              authenticateRole: 'Neos.IdNeosIo:NeosCommunityMember'
          CrowdProvider:
            provider: Neos\CrowdClient\Security\Authentication\Provider\CrowdProvider
            providerOptions:
              crowdApplicationName: idneosio
              crowdApplicationPassword: verysecretapplicationpasswordgoeshere
              authenticateRole: 'Neos.IdNeosIo:NeosCommunityMember'
            requestPatterns:
              'Neos.IdNeosIo:NoTokenRequest':
                pattern: Neos\IdNeosIo\Security\RequestPattern\NoTokenRequestPattern
            entryPoint: WebRedirect
            entryPointOptions:
              routeValues:
                '@package': Neos.IdNeosIo
                '@controller': Login
                '@action': login
                '@format': html
  IdNeosIo:
    crowdApplicationName: idneosio
    crowdApplicationPassword: verysecretapplicationpasswordgoeshere
    authenticationProviderName: CrowdProvider
Flownative:
  DoubleOptIn:
    presets:
      default:
        activation:
          uri:
            '@package': Neos.IdNeosIo
            '@format': html
            arguments:
              token: '-tokenhash-'
        mail:
          from:
            name: 'Neos Community'
            address: no-reply@neos.io
      'id.neos.io registration':
        activation:
          uri:
            '@controller': User
            '@action': activate
        mail:
          subject: 'Activate your Neos community account'
          message:
            plaintext: 'resource://Neos.IdNeosIo/Private/Templates/User/ActivationMail.txt'
      'id.neos.io reset password':
        activation:
          uri:
            '@controller': ResetPassword
            '@action': form
        mail:
          subject: 'Reset password for your Neos community account'
          message:
            plaintext: 'resource://Neos.IdNeosIo/Private/Templates/ResetPassword/ResetPasswordMail.txt'
      'id.neos.io change email':
        activation:
          uri:
            '@controller': User
            '@action': confirmEmail
        mail:
          subject: 'Confirm your Neos community email address'
          message:
            plaintext: 'resource://Neos.IdNeosIo/Private/Templates/User/ConfirmEmailAddress.txt'
